// <auto-generated />
namespace BlueBadge.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FullNameforUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullNameforUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202111022127570_FullName for User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
